"""initial

Revision ID: 3212a1b9e5e7
Revises: 3317cd468e96
Create Date: 2024-08-03 19:23:48.835114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3212a1b9e5e7'
down_revision: Union[str, None] = '3317cd468e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('register_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('boosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fill_char_count', sa.Integer(), nullable=False),
    sa.Column('charge_count', sa.Integer(), nullable=False),
    sa.Column('mine_coint', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('img_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['img_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achivments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('up_50k', sa.Boolean(), nullable=False),
    sa.Column('up_100k', sa.Boolean(), nullable=False),
    sa.Column('up_500k', sa.Boolean(), nullable=False),
    sa.Column('up_1million', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clan_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_id_clan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_id_clan')
    op.drop_table('clan_score')
    op.drop_table('user_score')
    op.drop_table('user_achivments')
    op.drop_table('clan')
    op.drop_table('charge')
    op.drop_table('boosts')
    op.drop_table('user_account')
    op.drop_table('image')
    # ### end Alembic commands ###
