"""users achivments

Revision ID: 3738cf031c8a
Revises: a37656171599
Create Date: 2024-07-10 18:29:01.993193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3738cf031c8a'
down_revision: Union[str, None] = 'a37656171599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charge')
    # ### end Alembic commands ###
