"""Initial migration

Revision ID: a0d05b38ad2f
Revises: cd8fc3c7271c
Create Date: 2024-05-30 15:36:37.412182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d05b38ad2f'
down_revision: Union[str, None] = 'cd8fc3c7271c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
