"""Initial migration

Revision ID: e46657e76daf
Revises: a0d05b38ad2f
Create Date: 2024-05-30 15:44:41.395847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46657e76daf'
down_revision: Union[str, None] = 'a0d05b38ad2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('description', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
