"""users charge

Revision ID: 3317cd468e96
Revises: 95c7664dbcb4
Create Date: 2024-07-11 15:45:11.166345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3317cd468e96'
down_revision: Union[str, None] = '95c7664dbcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge', sa.Column('user', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
