"""users achivments

Revision ID: a37656171599
Revises: 9e529ee0c5e5
Create Date: 2024-06-18 19:18:14.613715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37656171599'
down_revision: Union[str, None] = '9e529ee0c5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achivments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('up_50k', sa.Boolean(), nullable=False),
    sa.Column('up_100k', sa.Boolean(), nullable=False),
    sa.Column('up_500k', sa.Boolean(), nullable=False),
    sa.Column('up_1million', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achivments')
    # ### end Alembic commands ###
